/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package EmployeeRegwithDB;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class ViewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudent
     */
    public ViewEmployee() throws ClassNotFoundException, SQLException {
        initComponents();
	data=db.getAllData();
        tb.setModel(new javax.swing.table.DefaultTableModel(data,heading));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtngroup = new javax.swing.ButtonGroup();
        rbpanel = new javax.swing.JPanel();
        rball = new javax.swing.JRadioButton();
        rbit = new javax.swing.JRadioButton();
        rbsale = new javax.swing.JRadioButton();
        rbmarketing = new javax.swing.JRadioButton();
        rboffice = new javax.swing.JRadioButton();
        tbpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btnpanel = new javax.swing.JPanel();
        btnview = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rbtngroup.add(rball);
        rball.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rball.setForeground(java.awt.Color.blue);
        rball.setText("All Departments");
        rball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rballActionPerformed(evt);
            }
        });

        rbtngroup.add(rbit);
        rbit.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rbit.setForeground(java.awt.Color.blue);
        rbit.setText("IT");

        rbtngroup.add(rbsale);
        rbsale.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rbsale.setForeground(java.awt.Color.blue);
        rbsale.setText("Sale");
        rbsale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsaleActionPerformed(evt);
            }
        });

        rbtngroup.add(rbmarketing);
        rbmarketing.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rbmarketing.setForeground(java.awt.Color.blue);
        rbmarketing.setText("Marketing");
        rbmarketing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmarketingActionPerformed(evt);
            }
        });

        rbtngroup.add(rboffice);
        rboffice.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        rboffice.setForeground(new java.awt.Color(0, 0, 255));
        rboffice.setText("Office");

        javax.swing.GroupLayout rbpanelLayout = new javax.swing.GroupLayout(rbpanel);
        rbpanel.setLayout(rbpanelLayout);
        rbpanelLayout.setHorizontalGroup(
            rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rbpanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rball)
                    .addComponent(rbmarketing))
                .addGap(23, 23, 23)
                .addGroup(rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rboffice)
                    .addGroup(rbpanelLayout.createSequentialGroup()
                        .addComponent(rbit)
                        .addGap(52, 52, 52)
                        .addComponent(rbsale)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rbpanelLayout.setVerticalGroup(
            rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rbpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rball)
                    .addComponent(rbit)
                    .addComponent(rbsale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(rbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbmarketing)
                    .addComponent(rboffice)))
        );

        jScrollPane1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jScrollPane1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tb.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(tb);

        javax.swing.GroupLayout tbpanelLayout = new javax.swing.GroupLayout(tbpanel);
        tbpanel.setLayout(tbpanelLayout);
        tbpanelLayout.setHorizontalGroup(
            tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        tbpanelLayout.setVerticalGroup(
            tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnview.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        btnview.setForeground(java.awt.Color.blue);
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        btnclose.setFont(new java.awt.Font("Serif", 0, 16)); // NOI18N
        btnclose.setForeground(java.awt.Color.blue);
        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnpanelLayout = new javax.swing.GroupLayout(btnpanel);
        btnpanel.setLayout(btnpanelLayout);
        btnpanelLayout.setHorizontalGroup(
            btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnpanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnview)
                .addGap(52, 52, 52)
                .addComponent(btnclose)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        btnpanelLayout.setVerticalGroup(
            btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnpanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(btnpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnview)
                    .addComponent(btnclose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rbpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
	String dept="";
	if(rball.isSelected())
            dept="Alldept";
	if(rbit.isSelected())
            dept="IT";
	if(rbsale.isSelected())
            dept="Sale";
	if(rbmarketing.isSelected())
            dept="Marketing";
	if(rboffice.isSelected())
            dept="Office";
	tbpanel.removeAll();
	if(dept.equals("Alldept"))
            {
		try {
                	data=db.getAllData();
                        tb.setModel(new javax.swing.table.DefaultTableModel(data,heading));
                        jScrollPane1.setViewportView(tb);
                        javax.swing.GroupLayout tbpanelLayout = new javax.swing.GroupLayout(tbpanel);
                        tbpanel.setLayout(tbpanelLayout);
                        tbpanelLayout.setHorizontalGroup(
                            tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        );
                        tbpanelLayout.setVerticalGroup(
                            tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        );
                    } catch (ClassNotFoundException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                    } catch (SQLException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                    }
            }
            else
            {
		tbpanel.removeAll();
		try {
                	data=db.getDatabyDept(dept);
                        tb.setModel(new javax.swing.table.DefaultTableModel(data,heading));
                        jScrollPane1.setViewportView(tb);
                        javax.swing.GroupLayout tbpanelLayout = new javax.swing.GroupLayout(tbpanel);
                        tbpanel.setLayout(tbpanelLayout);
                        tbpanelLayout.setHorizontalGroup(
                            tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        );
                        tbpanelLayout.setVerticalGroup(
                            tbpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        );
		} catch (ClassNotFoundException e1) {
		// TODO Auto-generated catch block
		e1.printStackTrace();
		} catch (SQLException e1) {
		// TODO Auto-generated catch block
		e1.printStackTrace();
		}
            }
    }//GEN-LAST:event_btnviewActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void rbmarketingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmarketingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbmarketingActionPerformed

    private void rbsaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbsaleActionPerformed

    private void rballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rballActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rballActionPerformed

    private void jScrollPane1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jScrollPane1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewEmployee().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ViewEmployee.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    String[] heading={"RollNo","Name","Address","Salary($)","Rank","Dept"};
    String[][] data;
    DataBaseConnection db=new DataBaseConnection();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JPanel btnpanel;
    private javax.swing.JButton btnview;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rball;
    private javax.swing.JRadioButton rbit;
    private javax.swing.JRadioButton rbmarketing;
    private javax.swing.JRadioButton rboffice;
    private javax.swing.JPanel rbpanel;
    private javax.swing.JRadioButton rbsale;
    private javax.swing.ButtonGroup rbtngroup;
    private javax.swing.JTable tb;
    private javax.swing.JPanel tbpanel;
    // End of variables declaration//GEN-END:variables
}
